# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: reaction.proto for package 'reaction'

require 'grpc'
require 'reaction_pb'

module Reaction
  module ReactionService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'reaction.ReactionService'

      rpc :CreateLike, ::Reaction::CreateLikeRequest, ::Reaction::CreateLikeResponse
    end

    Stub = Service.rpc_stub_class
  end
end
