# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reaction.proto

require 'google/protobuf'


descriptor_data = "\n\x0ereaction.proto\x12\x08reaction\"5\n\x11\x43reateLikeRequest\x12\x0f\n\x07post_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\"%\n\x12\x43reateLikeResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2Z\n\x0fReactionService\x12G\n\nCreateLike\x12\x1b.reaction.CreateLikeRequest\x1a\x1c.reaction.CreateLikeResponseb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Reaction
  CreateLikeRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("reaction.CreateLikeRequest").msgclass
  CreateLikeResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("reaction.CreateLikeResponse").msgclass
end
