default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
  database: <%= ENV['DB_NAME' || 'reactions'] %>
  port: <%= ENV['DB_PORT'] || 5432 %> 

development:
  <<: *default
  database: <%= ENV['DB_NAME'] || 'reactions' %>

production:
  <<: *default
  database: <%= ENV['DB_NAME'] || 'reactions' %>
  username: <%= ENV['DB_USERNAME'] || 'alexis' %>
  password: <%= ENV['DB_PASSWORD'] || 'admin123' %>
  host: <%= ENV['DB_HOST'] || 'lumisnap-db.cpiel8qemsnc.us-east-1.rds.amazonaws.com' %>
